language: python

git:
    depth: 1

matrix:
    include:
        - python: 2.7
          os: linux
          env: BUILD_COMMAND=sdist

        - python: 3.4
          os: linux
          env: BUILD_COMMAND=sdist

        - python: 3.5
          os: linux
          env: BUILD_COMMAND=sdist

        - language: generic
          os: osx
          env: BUILD_COMMAND=bdist_wheel

cache:
    apt: true

install:
    # Mac OS X specific bootstrap
    - source ./ci/travis_osx.sh
    - travis_osx_install_begin

    # Upgrade distribution modules
    - pip install --upgrade setuptools
    - python -m pip install --upgrade pip

    # Install build dependencies
    - pip install --upgrade wheel
    #- pip install --trusted-host www.silx.org --find-links http://www.silx.org/pub/wheelhouse/ h5py --no-index

    # Print Python info
    - python ./ci/info_platform.py
    - pip list

    # Generate source package or wheel
    - python setup.py $BUILD_COMMAND
    - ls dist

    # Mac OS X specific cleanup
    - travis_osx_install_end

script:
    # Mac OS X specific bootstrap
    - travis_osx_run_begin

    # Upgrade distribution modules
    - pip install --upgrade setuptools
    - python -m pip install --upgrade pip

    # Install h5py for tests
    - pip install --pre --find-links dist/ --trusted-host www.silx.org --find-links http://www.silx.org/pub/wheelhouse/ h5py

    # Install built package
    # Make sure it does not come from cache or pypi
    # At this point all install_requires dependencies MUST be installed
    # as this is installing only from dist
    - pip install --pre --find-links dist/ --no-cache-dir --no-index hdf5plugin

    # Print Python info
    - python ci/info_platform.py
    - pip list

    # Run the tests
    - python test/test.py

    # Mac OS X specific cleanup
    - travis_osx_run_end
